backend:
  image:
    repository: 666607745270.dkr.ecr.ap-southeast-2.amazonaws.com/careercrafter-backend
    tag: 1a65a74fade698b2ebd9553bf5e27cfc8e50fa5b
  serviceAccount:
    name: backend-sa
    roleArn: arn:aws:iam::666607745270:role/eksctl-careercrafter-cluster-addon-iamservice-Role1-LwyQ8MGwCw0S

frontend:
  image:
    repository: 666607745270.dkr.ecr.ap-southeast-2.amazonaws.com/careercrafter-frontend
    tag: 1a65a74fade698b2ebd9553bf5e27cfc8e50fa5b
