backend:
  image:
    repository: 666607745270.dkr.ecr.ap-southeast-2.amazonaws.com/careercrafter-backend
    tag: 884aee89a71e007d5c54feec3d902b83d1fe144f
  serviceAccount:
    name: backend-sa
    roleArn: arn:aws:iam::666607745270:role/eksctl-careercrafter-cluster-addon-iamservice-Role1-LwyQ8MGwCw0S

frontend:
  image:
    repository: 666607745270.dkr.ecr.ap-southeast-2.amazonaws.com/careercrafter-frontend
    tag: 884aee89a71e007d5c54feec3d902b83d1fe144f
