services:
  backend:
    image: ${DOCKERHUB_USERNAME:-careercrafter}/${DOCKERHUB_BACKEND_REPOSITORY:-careercrafter-backend}:latest
    build:
      context: ./backend_careercrafter
      dockerfile: Dockerfile
    container_name: careercrafter-backend
    env_file:
      - ./backend_careercrafter/.env
    expose:
      - "8084"
    restart: unless-stopped
    networks:
      - career-network

  frontend:
    image: ${DOCKERHUB_USERNAME:-careercrafter}/${DOCKERHUB_FRONTEND_REPOSITORY:-careercrafter-frontend}:latest
    build:
      context: ./frontend_careercrafter
      dockerfile: Dockerfile
    container_name: careercrafter-frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - career-network

networks:
  career-network:
    driver: bridge
