apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend

spec:
  replicas: 2

  selector:
    matchLabels:
      app: frontend

  template:

    metadata:
      labels:
        app: frontend

    spec:

      containers:

      - name: frontend

        image: 666607745270.dkr.ecr.ap-southeast-2.amazonaws.com/careercrafter-frontend:latest

        ports:
        - containerPort: 80