ROLE_EMPLOYER = "EMPLOYER"
ROLE_JOBSEEKER = "JOBSEEKER"
VALID_ROLES = (ROLE_EMPLOYER, ROLE_JOBSEEKER)

VALID_APPLICATION_STATUSES = ("Applied", "Shortlisted", "Rejected", "Selected")
APPLICATION_STATUS_BY_INPUT = {
    status.lower(): status for status in VALID_APPLICATION_STATUSES
}

PHONE_NUMBER_LENGTH = 10

VALID_JOB_SEARCH_FIELDS = ("title", "location")
