ROLE_EMPLOYER = "EMPLOYER"
ROLE_JOBSEEKER = "JOBSEEKER"
VALID_ROLES = (ROLE_EMPLOYER, ROLE_JOBSEEKER)

STATUS_APPLIED = "Applied"
STATUS_SHORTLISTED = "Shortlisted"
STATUS_REJECTED = "Rejected"
STATUS_SELECTED = "Selected"
VALID_APPLICATION_STATUSES = (
    STATUS_APPLIED,
    STATUS_SHORTLISTED,
    STATUS_REJECTED,
    STATUS_SELECTED,
)
APPLICATION_STATUS_BY_INPUT = {
    status.lower(): status for status in VALID_APPLICATION_STATUSES
}

PHONE_NUMBER_LENGTH = 10

SEARCH_FIELD_TITLE = "title"
SEARCH_FIELD_LOCATION = "location"
VALID_JOB_SEARCH_FIELDS = (SEARCH_FIELD_TITLE, SEARCH_FIELD_LOCATION)
