apiVersion: v1
kind: ConfigMap

metadata:
  name: backend-config

data:
  DB_URL: jdbc:mysql://careercrafter-db.cba86w080orf.ap-southeast-2.rds.amazonaws.com/careercrafter
  DB_USERNAME: admin
  AWS_REGION: ap-southeast-2
  S3_BUCKET: resumes-bucket-careercrafter
  JWT_EXPIRATION_MS: "10800000"
