apiVersion: v1
kind: Secret

metadata:
   name: backend-secret

type: Opaque

stringData:
   DB_PASSWORD: Immunoglobin812
   JWT_SECRET: 3d9a7b1c9d6e2f4a8c1b5d9e7a3f6c2b4e8d1a7c9f5b2e6d3a8c4f1b7e9d2b5
