-- CareerCrafter Database Schema

-- 1. USER Table
CREATE TABLE USER (
    PK_userID INT PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role ENUM('JOB_SEEKER', 'EMPLOYER') NOT NULL DEFAULT 'JOB_SEEKER',
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- 2. JOB_SEEKER Table
CREATE TABLE JOB_SEEKER (
    PK_seekerID INT PRIMARY KEY AUTO_INCREMENT,
    FK_userID INT NOT NULL UNIQUE,
    firstName VARCHAR(100) NOT NULL,
    lastName VARCHAR(100) NOT NULL,
    phone VARCHAR(20),
    location VARCHAR(255),
    FOREIGN KEY (FK_userID) REFERENCES USER(PK_userID) ON DELETE CASCADE
);

-- 3. EMPLOYER Table
CREATE TABLE EMPLOYER (
    PK_employerID INT PRIMARY KEY AUTO_INCREMENT,
    FK_userID INT NOT NULL UNIQUE,
    contactFirstName VARCHAR(100),
    contactLastName VARCHAR(100),
    companyName VARCHAR(255) NOT NULL,
    industry VARCHAR(100),
    website VARCHAR(255),
    verifiedStatus ENUM('PENDING', 'VERIFIED', 'REJECTED') DEFAULT 'PENDING',
    FOREIGN KEY (FK_userID) REFERENCES USER(PK_userID) ON DELETE CASCADE
);

-- 4. JOB_LISTING Table
CREATE TABLE JOB_LISTING (
    PK_jobID INT PRIMARY KEY AUTO_INCREMENT,
    FK_employerID INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    requirements TEXT,
    location VARCHAR(255),
    jobType ENUM('FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERNSHIP', 'REMOTE') DEFAULT 'FULL_TIME',
    salaryMin DECIMAL(10, 2),
    salaryMax DECIMAL(10, 2),
    postedDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    deadline DATETIME,
    status ENUM( 'ACTIVE', 'CLOSED') DEFAULT 'ACTIVE',
    FOREIGN KEY (FK_employerID) REFERENCES EMPLOYER(PK_employerID) ON DELETE CASCADE
);

-- 5. APPLICATION Table
CREATE TABLE APPLICATION (
    PK_applicationID INT PRIMARY KEY AUTO_INCREMENT,
    FK_jobID INT NOT NULL,
    FK_seekerID INT NOT NULL,
    status ENUM('APPLIED', 'UNDER_REVIEW', 'SHORTLISTED', 'OFFER_EXTENDED', 'REJECTED') DEFAULT 'APPLIED',
    appliedDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    coverLetter TEXT,
    FOREIGN KEY (FK_jobID) REFERENCES JOB_LISTING(PK_jobID) ON DELETE CASCADE,
    FOREIGN KEY (FK_seekerID) REFERENCES JOB_SEEKER(PK_seekerID) ON DELETE CASCADE,
    UNIQUE (FK_jobID, FK_seekerID)
);

-- 6. RESUME Table
CREATE TABLE RESUME (
    PK_resumeID INT PRIMARY KEY AUTO_INCREMENT,
    FK_seekerID INT NOT NULL,
    fileURL VARCHAR(500) NOT NULL,
    fileName VARCHAR(255) NOT NULL,
    fileType ENUM('PDF', 'DOC', 'DOCX') DEFAULT 'PDF',
    isDefault BOOLEAN DEFAULT FALSE,
    visibility ENUM('PUBLIC', 'PRIVATE', 'EMPLOYERS_ONLY') DEFAULT 'PUBLIC',
    FOREIGN KEY (FK_seekerID) REFERENCES JOB_SEEKER(PK_seekerID) ON DELETE CASCADE
);

-- 7. EDUCATION Table
CREATE TABLE EDUCATION (
    PK_educationID INT PRIMARY KEY AUTO_INCREMENT,
    FK_seekerID INT NOT NULL,
    institution VARCHAR(255) NOT NULL,
    degree VARCHAR(100),
    fieldOfStudy VARCHAR(100),
    graduationDate DATE,
    grade VARCHAR(50),
    FOREIGN KEY (FK_seekerID) REFERENCES JOB_SEEKER(PK_seekerID) ON DELETE CASCADE
);

-- 8. WORK_EXPERIENCE Table
CREATE TABLE WORK_EXPERIENCE (
    PK_experienceID INT PRIMARY KEY AUTO_INCREMENT,
    FK_seekerID INT NOT NULL,
    company VARCHAR(255) NOT NULL,
    position VARCHAR(255) NOT NULL,
    startDate DATE,
    endDate DATE,
    location VARCHAR(255),
    description TEXT,
    FOREIGN KEY (FK_seekerID) REFERENCES JOB_SEEKER(PK_seekerID) ON DELETE CASCADE
);

-- 9. SKILL Table
CREATE TABLE SKILL (
    PK_skillID INT PRIMARY KEY AUTO_INCREMENT,
    skillName VARCHAR(100) NOT NULL UNIQUE,
    
);

-- 10. SEEKER_SKILL Table
CREATE TABLE SEEKER_SKILL (
    PK_seekerSkillID INT PRIMARY KEY AUTO_INCREMENT,
    FK_seekerID INT NOT NULL,
    FK_skillID INT NOT NULL,
    FOREIGN KEY (FK_seekerID) REFERENCES JOB_SEEKER(PK_seekerID) ON DELETE CASCADE,
    FOREIGN KEY (FK_skillID) REFERENCES SKILL(PK_skillID) ON DELETE CASCADE,
    UNIQUE (FK_seekerID, FK_skillID)
);

-- 11. NOTIFICATION Table
CREATE TABLE NOTIFICATION (
    PK_notificationID INT PRIMARY KEY AUTO_INCREMENT,
    FK_userID INT NOT NULL,
    type ENUM('APPLICATION_UPDATE', 'NEW_JOB_MATCH', 'MESSAGE', 'SYSTEM_ALERT') DEFAULT 'SYSTEM_ALERT',
    message TEXT,
    isRead BOOLEAN DEFAULT FALSE,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (FK_userID) REFERENCES USER(PK_userID) ON DELETE CASCADE
);
