from utils.db_connection import get_connection
from model.application import Application
from exceptions.custom_exceptions import ApplicationStatusException


class ApplicationRepository:
    def __init__(self):
        self.conn = get_connection()

    def save(self, application: Application) -> None:
        """Insert a new application record into the database.
        The `application_id` is auto‑generated by the DB.
        """
        sql = """
        INSERT INTO applications (
            job_id,
            user_id,
            resume_id,
            phone_number,
            status
        ) VALUES (%s, %s, %s, %s, %s)
        """
        params = (
            application.job_id,
            application.user_id,
            application.resume_id,
            application.phone_number,
            application.status,
        )
        with self.conn.cursor() as cursor:
            cursor.execute(sql, params)
        self.conn.commit()

    def find_by_user(self, user_id: int) -> list:
        sql = """
        SELECT a.job_id, j.title, j.employer_id, a.status, a.applied_at
        FROM applications a
        JOIN jobs j ON a.job_id = j.job_id
        WHERE a.user_id = %s
        ORDER BY a.applied_at DESC
        """
        with self.conn.cursor() as cursor:
            cursor.execute(sql, (user_id,))
            rows = cursor.fetchall()
        
        result = []
        for job_id, title, employer_id, status, applied_at in rows:
            result.append({
                "job_id": job_id,
                "job_title": title,
                "company": employer_id,
                "status": status,
                "applied_at": applied_at,
            })
        return result

    def update_status(self, application_id: int, new_status: str) -> bool:

        sql = """
        UPDATE applications
        SET status = %s
        WHERE application_id = %s
        """
        try:
            with self.conn.cursor() as cursor:
                cursor.execute(sql, (new_status, application_id))
                affected = cursor.rowcount
            self.conn.commit()
            if affected == 0:
                from exceptions.custom_exceptions import ApplicationNotFoundException
                raise ApplicationNotFoundException(f"Application ID {application_id} not found.")
            return True
        except Exception as db_err:
            print(f"Database error updating status: {db_err}")
            return False

    def find_by_job(self, job_id: int) -> list:
        sql = """
        SELECT a.application_id,
               a.job_id,
               j.title           AS job_title,
               a.resume_id,
               r.qualification,
               r.experience,
               r.skills,
               u.name            AS applicant_name,
               a.phone_number,
               a.status
        FROM applications a
        JOIN jobs j ON a.job_id = j.job_id
        JOIN resumes r ON a.resume_id = r.resume_id
        JOIN users u ON a.user_id = u.user_id
        WHERE a.job_id = %s
        ORDER BY a.application_id
        """
        with self.conn.cursor(dictionary=True) as cursor:
            cursor.execute(sql, (job_id,))
            rows = cursor.fetchall()
        return rows
